export const teamAssociationCheckList: string[] = [
  "Board",
  "Camp",
  "Chair",
  "HH",
  "Lapsed Team",
  "Planning Comm",
  "RC Member/Team",
  "RC Secured",
  "Sponsor",
];

export const staffLead : string[] = [
  "Aaron Castens",
"Amy Btiebet Washington",
"Amy Carroll",
"Anna Wishneff",
"AnnaMaria Mindish",
"BaiLeigh Leach",
"Beth Jabick",
"Brittany Matteson",
"Caitlynn O'Halloran",
"Caroline Webel",
"Casey White",
"Catherine Pavlick",
"Cathy Miller",
"Chris Cwik",
"Claire Dennehy",
"Colton A. Lee",
"Dawn Halsey",
"Dawn Stock",
"Derek Dodson",
"Emily Gray",
"Emily Richter",
"Eric Hecker",
"Eric Israel",
"Eric Page",
"Erin Lewis",
"Erin Rome",
"Ginger L. Peace",
"Heather Anderson",
"Howard Pernell",
"Iris Magid",
"Jackie Peterson",
"James Stanphill",
"Janie Bortz",
"Jennifer Campbell",
"Jennifer O'Connor",
"Jenny Southers",
"Jessica Flannagan",
"Jessica Reiter-Flax",
"Joseph P. Cobucci",
"Joshua Woods",
"Julia Hamel",
"Juliane Kilcoyne",
"Kathleen M. Keohane",
"Kathryn Schroeder Owens",
"Katy Ahmed",
"Kerri Clifford",
"Kim Kaplan",
"Kimberly Brammer",
"Kira Gilbert",
"Kris A. Ference",
"Laura B. Kraubetz",
"Laurel Grimm",
"Lauren Wyngarden",
"Leslie Del Ponte",
"Linae Stoner",
"Linda Coughlan",
"Linda G. Winston",
"Lindsay Fujimoto",
"Linell Baumann",
"Lisa Harding",
"Lucille Tarsitano",
"Lynn Williams",
"Maggie Weisberg",
"Makenzie Diffley",
"Maria M. Jones",
"Marissa Spratley",
"Mary C. Esna-Ashari",
"Mary M. Rein",
"Megan Olson",
"Melanie Zhitnitsky",
"Melissa Pulsinelli Varellas",
"Meredith K. Wood",
"Michelle J. Chianese",
"Natascha Martin",
"Nealika Caden",
"Nicole Grischuk",
"Nicolette Illiano",
"Paddy Harrigan",
"Pamela Glickman",
"Paula Eichholz",
"Paulette Purnell",
"Peggy Merchant",
"Phillip Kauffman",
"Rebecca Herman",
"Robin Carr",
"Sam Wohlfeil",
"Sara Northrop",
"sarah K. arminiak",
"Sarah Wald",
"Summer L. Reyes",
"Susan A. Gomberg",
"Suzanne Beck",
"Vanessa Sher"
]