export const UPDATE_CHAPTER_LIST ='UPDATE_CHAPTER_LIST';
export const UPDATE_SELECTED_CHAPTER = 'UPDATE_SELECTED_CHAPTER';
export const UPDATE_EVENT_LIST = 'UPDATE_EVENT_LIST';
export const UPDATE_SELECTED_EVENT = 'UPDATE_SELECTED_EVENT';
export const CHANGE_DATA_FETCHING = 'CHANGE_DATA_FETCHING';
